# import * as _GenreOrdering from './GenreOrdering.gql'
# import * as _GenreFilter from './GenreFilter.gql'

query moviesByGenre(
  $id: String
  $name: String
  $first: Int
  $offset: Int
  $orderBy: [_GenreOrdering]
  $filter: _GenreFilter
  $userId: ID!
) {
  Genre(
    _id: $id
    name: $name
    first: $first
    offset: $offset
    orderBy: $orderBy
    filter: $filter
  ) {
    _id
    name
    movies(first: $first, orderBy: budget_desc) {
      movieId
      imdbRating
      title
      year
      poster

      in_genre(first: 3) {
        _id
        name
      }

      users_ratings(filter: { User: { userId: $userId } }) {
        rating
        timestamp
        User {
          userId
          name
        }
      }
    }
  }
}
