query RatedsByUser($userId: ID!) {
  User(userId: $userId) {
    RATED_rel {
      _id
      rating
      timestamp
      Movie {
        movieId
        title
        year
        imdbRating
        tmdbId
        poster

        in_genre(first: 3) {
          _id
          name
        }

        users_ratings(filter: { User: { userId: $userId } }) {
          rating
          timestamp
          User {
            userId
            name
          }
        }
      }
    }
  }
}
